In [1]:
## one hot encoding
from tensorflow.keras.preprocessing.text import one_hot
## Word Embedding
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [2]:
## Sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
## Define the vocabulary size 
voc_size = 10000
## One hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[1719, 4208, 9797, 6443],
 [1719, 4208, 9797, 109],
 [1719, 2850, 9797, 5452],
 [4890, 4756, 1352, 7036, 4036],
 [4890, 4756, 1352, 7036, 7060],
 [9097, 1719, 7365, 9797, 3696],
 [1758, 7432, 9273, 7036]]

In [4]:
import numpy as np

In [5]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1719 4208 9797 6443]
 [   0    0    0    0 1719 4208 9797  109]
 [   0    0    0    0 1719 2850 9797 5452]
 [   0    0    0 4890 4756 1352 7036 4036]
 [   0    0    0 4890 4756 1352 7036 7060]
 [   0    0    0 9097 1719 7365 9797 3696]
 [   0    0    0    0 1758 7432 9273 7036]]


In [6]:
## feature Representation
dim = 10


In [7]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 203ms/step


array([[[-0.02408331, -0.03686864,  0.02360172,  0.04839009,
         -0.0160486 ,  0.03569441,  0.02590665, -0.02616881,
          0.02503148, -0.038121  ],
        [-0.02408331, -0.03686864,  0.02360172,  0.04839009,
         -0.0160486 ,  0.03569441,  0.02590665, -0.02616881,
          0.02503148, -0.038121  ],
        [-0.02408331, -0.03686864,  0.02360172,  0.04839009,
         -0.0160486 ,  0.03569441,  0.02590665, -0.02616881,
          0.02503148, -0.038121  ],
        [-0.02408331, -0.03686864,  0.02360172,  0.04839009,
         -0.0160486 ,  0.03569441,  0.02590665, -0.02616881,
          0.02503148, -0.038121  ],
        [ 0.03939578, -0.03064185,  0.02084306, -0.00922209,
          0.00729082,  0.03545203, -0.03759144,  0.01264136,
         -0.04247061, -0.01447247],
        [ 0.0470233 ,  0.02133774, -0.01482365, -0.02917832,
          0.02621381,  0.04946217, -0.03356781, -0.02023859,
         -0.00790954,  0.02767881],
        [ 0.02182169, -0.01345416,  0.04617867,  0.0